"""gate-mcp — guild-cli gate commands as MCP tools.

Thin subprocess wrapper around `node bin/gate.mjs`.
Designed for Claude Code integration via .mcp.json.

Requires: mcp >= 1.25.0 (FastMCP)
"""

from __future__ import annotations

import asyncio
import json
import os
import sys
from pathlib import Path
from typing import Any

from mcp.server.fastmcp import FastMCP

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

GUILD_CLI_DIR = os.environ.get(
    "GUILD_CLI_DIR",
    str(Path(__file__).resolve().parent.parent),
)
GATE_BIN = str(Path(GUILD_CLI_DIR) / "bin" / "gate.mjs")
GUILD_BIN = str(Path(GUILD_CLI_DIR) / "bin" / "guild.mjs")

# content_root: where guild.config.yaml lives
_DEFAULT_CONTENT_ROOT = os.environ.get("GATE_CONTENT_ROOT", "")
_PROJECTS_DIR = os.environ.get(
    "GATE_PROJECTS_DIR",
    str(Path(_DEFAULT_CONTENT_ROOT) / "projects") if _DEFAULT_CONTENT_ROOT else "",
)

# Mutable — switched by gate_switch_project()
_current_content_root = _DEFAULT_CONTENT_ROOT
_current_project: str | None = None

mcp = FastMCP(
    "gate-mcp",
    instructions="guild-cli gate commands as MCP tools. Supports project switching via gate_switch_project().",
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _cwd() -> str | None:
    """Return the current content root for subprocess cwd."""
    return _current_content_root or None


async def _run_gate(*args: str, stdin_text: str | None = None) -> str:
    """Run gate CLI and return stdout unmodified. Raises on non-zero exit.

    stderr is never mixed into stdout: agents consuming --format json would
    otherwise see "[stderr] ..." suffixed after valid JSON and fail to parse.
    Diagnostic stderr is forwarded to the MCP host's stderr for observability.
    """
    cmd = ["node", GATE_BIN, *args]
    proc = await asyncio.create_subprocess_exec(
        *cmd,
        stdin=asyncio.subprocess.PIPE if stdin_text else None,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
        cwd=_cwd(),
    )
    stdout, stderr = await proc.communicate(
        input=stdin_text.encode() if stdin_text else None
    )
    out = stdout.decode()
    err = stderr.decode().strip()
    if proc.returncode != 0:
        raise RuntimeError(f"gate exited {proc.returncode}: {err or out.strip()}")
    if err:
        print(f"[gate stderr] {err}", file=sys.stderr)
    return out


async def _run_guild(*args: str) -> str:
    """Run guild CLI and return stdout unmodified. stderr goes to host stderr."""
    cmd = ["node", GUILD_BIN, *args]
    proc = await asyncio.create_subprocess_exec(
        *cmd,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
        cwd=_cwd(),
    )
    stdout, stderr = await proc.communicate()
    out = stdout.decode()
    err = stderr.decode().strip()
    if proc.returncode != 0:
        raise RuntimeError(f"guild exited {proc.returncode}: {err or out.strip()}")
    if err:
        print(f"[guild stderr] {err}", file=sys.stderr)
    return out


def _flag(name: str, value: str | None) -> list[str]:
    """Build --name value if value is truthy."""
    return [f"--{name}", value] if value else []


# ---------------------------------------------------------------------------
# Project switching
# ---------------------------------------------------------------------------

_PROJECT_CONFIG_TEMPLATE = """\
# Auto-generated by gate-mcp for project: {project}
content_root: .
host_names: [eris, nao]
paths:
  members: members
  requests: requests
  issues: issues
  inbox: inbox
"""


def _project_dir(project: str) -> Path:
    """Return the directory for a named project. Validates path stays under PROJECTS_DIR."""
    if not project or "/" in project or "\\" in project or project in (".", ".."):
        raise ValueError(f"Invalid project name: {project!r}")
    resolved = (Path(_PROJECTS_DIR) / project).resolve()
    base = Path(_PROJECTS_DIR).resolve()
    if not str(resolved).startswith(str(base) + os.sep) and resolved != base:
        raise ValueError(f"Project path escapes base: {project!r}")
    return resolved


@mcp.tool()
async def gate_switch_project(project: str | None = None) -> str:
    """Switch gate context to a project. Pass None or empty string to return to THS global.

    If the project directory doesn't exist yet, use gate_init_project() first.
    """
    global _current_content_root, _current_project

    if not project:
        _current_content_root = _DEFAULT_CONTENT_ROOT
        _current_project = None
        return f"Switched to global content root: {_DEFAULT_CONTENT_ROOT}"

    proj_dir = _project_dir(project)
    if not proj_dir.exists():
        return f"Project '{project}' not found at {proj_dir}. Use gate_init_project('{project}') to create it."

    config_file = proj_dir / "guild.config.yaml"
    if not config_file.exists():
        return f"Project directory exists but guild.config.yaml is missing at {config_file}."

    _current_content_root = str(proj_dir)
    _current_project = project
    return f"Switched to project '{project}' at {proj_dir}"


@mcp.tool()
async def gate_init_project(project: str) -> str:
    """Initialize a new project with guild.config.yaml, shared members, and empty request/issue dirs."""
    proj_dir = _project_dir(project)

    if proj_dir.exists() and (proj_dir / "guild.config.yaml").exists():
        return f"Project '{project}' already exists at {proj_dir}"

    # Create directories
    for subdir in ["requests/pending", "requests/completed", "issues", "inbox"]:
        (proj_dir / subdir).mkdir(parents=True, exist_ok=True)

    # Symlink members from global content root (shared across projects)
    members_link = proj_dir / "members"
    if not members_link.exists():
        global_members = Path(_DEFAULT_CONTENT_ROOT) / "members"
        if global_members.exists():
            members_link.symlink_to(global_members.resolve())

    # Write config
    config_file = proj_dir / "guild.config.yaml"
    config_file.write_text(_PROJECT_CONFIG_TEMPLATE.format(project=project))

    return f"Initialized project '{project}' at {proj_dir}\n  members: symlinked from global\n  requests/issues/inbox: project-local"


@mcp.tool()
async def gate_list_projects() -> str:
    """List available gate projects."""
    global _current_project
    projects_dir = Path(_PROJECTS_DIR)
    if not projects_dir.exists():
        return "No projects directory found."

    projects = sorted(
        d.name for d in projects_dir.iterdir()
        if d.is_dir() and (d / "guild.config.yaml").exists()
    )

    if not projects:
        return "No projects initialized yet. Use gate_init_project() to create one."

    lines = []
    for p in projects:
        marker = " (active)" if p == _current_project else ""
        lines.append(f"  - {p}{marker}")

    current = _current_project or "(global)"
    return f"Current: {current}\nProjects:\n" + "\n".join(lines)


# ---------------------------------------------------------------------------
# Read tools
# ---------------------------------------------------------------------------

@mcp.tool()
async def gate_tail(n: int = 20) -> str:
    """Show the N most recent utterances (reviews, status changes) across all actors."""
    return await _run_gate("tail", str(n))


@mcp.tool()
async def gate_show(request_id: str, format: str = "text") -> str:
    """Show details of a specific request. format: 'text' or 'json'."""
    return await _run_gate("show", request_id, "--format", format)


@mcp.tool()
async def gate_list(state: str = "pending", for_actor: str | None = None,
                    from_actor: str | None = None) -> str:
    """List requests filtered by state. States: pending|approved|executing|completed|failed|denied."""
    args = ["list", "--state", state]
    args += _flag("for", for_actor)
    args += _flag("from", from_actor)
    return await _run_gate(*args)


@mcp.tool()
async def gate_pending(for_actor: str | None = None) -> str:
    """Shortcut for listing pending requests."""
    args = ["pending"]
    args += _flag("for", for_actor)
    return await _run_gate(*args)


@mcp.tool()
async def gate_voices(name: str, lense: str | None = None,
                      verdict: str | None = None, limit: int | None = None,
                      format: str = "text") -> str:
    """Show cross-cutting history for a specific actor."""
    args = ["voices", name, "--format", format]
    args += _flag("lense", lense)
    args += _flag("verdict", verdict)
    if limit:
        args += ["--limit", str(limit)]
    return await _run_gate(*args)


@mcp.tool()
async def gate_chain(id: str) -> str:
    """Show the chain of related requests/issues for a given ID."""
    return await _run_gate("chain", id)


# ---------------------------------------------------------------------------
# Write tools — request lifecycle
# ---------------------------------------------------------------------------

@mcp.tool()
async def gate_request(from_actor: str, action: str, reason: str,
                       executor: str | None = None,
                       auto_review: str | None = None,
                       target: str | None = None) -> str:
    """Create a new request."""
    args = ["request", "--from", from_actor, "--action", action, "--reason", reason]
    args += _flag("executor", executor)
    args += _flag("auto-review", auto_review)
    args += _flag("target", target)
    return await _run_gate(*args)


@mcp.tool()
async def gate_fast_track(from_actor: str, action: str, reason: str,
                          executor: str | None = None,
                          auto_review: str | None = None,
                          note: str | None = None) -> str:
    """One-shot request: pending → approved → executing → completed in one call."""
    args = ["fast-track", "--from", from_actor, "--action", action, "--reason", reason]
    args += _flag("executor", executor)
    args += _flag("auto-review", auto_review)
    args += _flag("note", note)
    return await _run_gate(*args)


@mcp.tool()
async def gate_approve(request_id: str, by: str, note: str | None = None) -> str:
    """Approve a pending request."""
    args = ["approve", request_id, "--by", by]
    args += _flag("note", note)
    return await _run_gate(*args)


@mcp.tool()
async def gate_execute(request_id: str, by: str, note: str | None = None) -> str:
    """Mark a request as executing."""
    args = ["execute", request_id, "--by", by]
    args += _flag("note", note)
    return await _run_gate(*args)


@mcp.tool()
async def gate_complete(request_id: str, by: str, note: str | None = None) -> str:
    """Mark a request as completed."""
    args = ["complete", request_id, "--by", by]
    args += _flag("note", note)
    return await _run_gate(*args)


@mcp.tool()
async def gate_deny(request_id: str, by: str, reason: str) -> str:
    """Deny a pending request."""
    return await _run_gate("deny", request_id, "--by", by, reason)


@mcp.tool()
async def gate_fail(request_id: str, by: str, reason: str) -> str:
    """Mark a request as failed."""
    return await _run_gate("fail", request_id, "--by", by, reason)


# ---------------------------------------------------------------------------
# Write tools — review
# ---------------------------------------------------------------------------

@mcp.tool()
async def gate_review(request_id: str, by: str, lense: str, verdict: str,
                      comment: str | None = None) -> str:
    """Add a review to a request. lense: devil|layer|cognitive|user. verdict: ok|concern|reject."""
    args = ["review", request_id, "--by", by, "--lense", lense, "--verdict", verdict]
    if comment:
        args += ["--comment", comment]
    return await _run_gate(*args)


# ---------------------------------------------------------------------------
# Issues
# ---------------------------------------------------------------------------

@mcp.tool()
async def gate_issues_list(state: str | None = None) -> str:
    """List issues. Optional state filter: open|in_progress|deferred|resolved."""
    args = ["issues", "list"]
    args += _flag("state", state)
    return await _run_gate(*args)


@mcp.tool()
async def gate_issues_add(from_actor: str, severity: str, area: str,
                          text: str) -> str:
    """Add a new issue. severity: low|med|high. area: free text."""
    return await _run_gate("issues", "add", "--from", from_actor,
                           "--severity", severity, "--area", area, text)


@mcp.tool()
async def gate_issues_transition(issue_id: str, verb: str) -> str:
    """Transition an issue state. verb: resolve|defer|start|reopen."""
    if verb not in ("resolve", "defer", "start", "reopen"):
        raise ValueError(f"Invalid verb: {verb}. Use resolve|defer|start|reopen")
    return await _run_gate("issues", verb, issue_id)


# ---------------------------------------------------------------------------
# Messages
# ---------------------------------------------------------------------------

@mcp.tool()
async def gate_message(from_actor: str, to: str, text: str) -> str:
    """Send a direct message to another member."""
    return await _run_gate("message", "--from", from_actor, "--to", to, "--text", text)


@mcp.tool()
async def gate_broadcast(from_actor: str, text: str) -> str:
    """Broadcast a message to all members."""
    return await _run_gate("broadcast", "--from", from_actor, "--text", text)


@mcp.tool()
async def gate_inbox(for_actor: str) -> str:
    """Read inbox messages for a member."""
    return await _run_gate("inbox", "--for", for_actor)


# ---------------------------------------------------------------------------
# Guild (member management)
# ---------------------------------------------------------------------------

@mcp.tool()
async def guild_list() -> str:
    """List all guild members."""
    return await _run_guild("list")


@mcp.tool()
async def guild_show(name: str) -> str:
    """Show member details."""
    return await _run_guild("show", name)


# ---------------------------------------------------------------------------
# Status (agent orientation)
# ---------------------------------------------------------------------------

@mcp.tool()
async def gate_status(for_actor: str | None = None, format: str = "json") -> str:
    """Agent orientation: pending/approved/executing counts, open issues, inbox unread.
    Default JSON output. Use --format text for human-readable."""
    args = ["status", "--format", format]
    args += _flag("for", for_actor)
    return await _run_gate(*args)


# ---------------------------------------------------------------------------
# Diagnostic
# ---------------------------------------------------------------------------

@mcp.tool()
async def gate_doctor(format: str = "text") -> str:
    """Run read-only health check over the content root."""
    args = ["doctor"]
    if format == "json":
        args += ["--format", "json"]
    elif format == "summary":
        args += ["--summary"]
    return await _run_gate(*args)


# ---------------------------------------------------------------------------
# MCP Apps — 判断履歴を「会話の中」に出す窓
#
# `io.modelcontextprotocol/ui` 拡張 (MCP spec 2026-07-28 で正式な拡張として登録)。
# tool の `_meta.ui.resourceUri` が `ui://` を指すと、対応ホストはその HTML を
# サンドボックス iframe で会話内にレンダリングする。
#
# ⚠️ **gate CLI が SOT のまま。これは窓であって本体ではない。**
#    既存の tool 群も substrate も一切変えない。CLI にできないこと ──
#    「誰が・いつ・何を決めたか」を *話している流れの隣に置く* ── だけを担う。
#
# ⚠️ **ホスト対応はクライアント依存。** 2026-07-31 時点の client-matrix では
#    Claude (web) / Claude Desktop / VS Code Copilot / Cursor / ChatGPT 他が対応、
#    **Claude Code (CLI) の行は無い**。非対応ホストでは `_meta` が無視され、
#    `gate_board` はただのテキスト tool として動く (壊れない)。
# ---------------------------------------------------------------------------

BOARD_UI_URI = "ui://gate/board"

# ⚠️ **1 枚に同梱する。** MCP Apps は `_meta.ui.csp` で明示しない限り外部オリジンを
#    読めない。CDN を使わない = 制約への追従であると同時に、example の依存を増やさない。
_BOARD_HTML = """<!doctype html>
<meta charset="utf-8">
<style>
  :root { color-scheme: light dark; }
  body { font: 13px/1.65 ui-monospace, SFMono-Regular, Menlo, monospace; margin: 0; padding: 14px; }
  h1 { font-size: 13px; margin: 0 0 12px; letter-spacing: .06em; opacity: .75; }
  .e { border-left: 3px solid currentColor; padding: 2px 0 2px 11px; margin: 0 0 11px; }
  .h { display: flex; gap: 9px; align-items: baseline; flex-wrap: wrap; }
  .id { font-weight: 700; }
  .kind { font-size: 11px; padding: 0 6px; border: 1px solid currentColor; border-radius: 3px; opacity: .7; }
  .at, .by { opacity: .55; font-size: 11px; }
  .action { margin: 3px 0 0; }
  .reason { opacity: .72; margin: 2px 0 0; }
  .note { opacity: .55; margin: 2px 0 0; font-size: 12px; }
  .empty { opacity: .6; }
</style>
<h1>gate — 判断の履歴</h1>
<div id="root" class="empty">ホストからのデータを待っている…</div>
<script>
function esc(s) {
  // ⚠️ **innerHTML に生の substrate を流さない。** action/reason は人間が書く自由文で、
  //    山括弧も引用符も入る。ここを飛ばすと substrate の中身が DOM になる。
  return String(s == null ? '' : s).replace(/[&<>"']/g,
    c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
}
function render(rows) {
  const root = document.getElementById('root');
  if (!Array.isArray(rows) || !rows.length) {
    root.textContent = '記録なし';
    return;
  }
  root.className = '';
  root.innerHTML = rows.map(r => `
    <div class="e">
      <div class="h">
        <span class="id">${esc(r.request_id)}</span>
        <span class="kind">${esc(r.kind)}</span>
        <span class="by">${esc(r.from)}</span>
        <span class="at">${esc((r.at || '').slice(0, 16).replace('T', ' '))}</span>
      </div>
      <div class="action">${esc(r.action)}</div>
      ${r.reason ? `<div class="reason">${esc(r.reason)}</div>` : ''}
      ${r.completion_note ? `<div class="note">↳ ${esc(r.completion_note)}</div>` : ''}
    </div>`).join('');
}
window.addEventListener('message', (e) => {
  // ⚠️ 仕様の細部 (ホストがどの形で push するか) は未検証なので、
  //    **受け取れた形を何であれ描く**。想定した形しか見ないと、
  //    届いているのに空に見えて原因を切り分けられなくなる。
  const d = e.data;
  for (const c of [d, d && d.params, d && d.result, d && d.params && d.params.data]) {
    if (Array.isArray(c)) { render(c); return; }
    if (c && Array.isArray(c.rows)) { render(c.rows); return; }
  }
});
// 初期表示はサーバが埋め込んだ値。push が来なくても空にしない
// (届いていないのか描けていないのかを、画面だけで切り分けるため)。
render(window.__GATE_BOARD__ || null);
</script>
"""


async def _board_rows(n: int) -> list[dict[str, Any]]:
    """`gate tail --format json` を読む。**JSON envelope が contract**（principle 11:
    substrate が contract、text は human projection）なので text を parse しない。"""
    raw = await _run_gate("tail", str(n), "--format", "json")
    try:
        rows = json.loads(raw)
    except json.JSONDecodeError:
        return []
    return rows if isinstance(rows, list) else []


@mcp.tool(
    # ⚠️ **これが MCP Apps の入口。** FastMCP は `meta=` を受け取り `_meta` として送る。
    #    (低レベル API の `types.Tool` では `meta=` が populate_by_name 無効のため
    #     黙って捨てられ `_meta` が null になる。あちらは `_meta=` で渡す必要がある)
    meta={"ui": {"resourceUri": BOARD_UI_URI}},
)
async def gate_board(n: int = 30) -> str:
    """Show recent gate decisions. Renders as an interactive board in hosts that
    support the MCP Apps extension; falls back to text elsewhere."""
    rows = await _board_rows(n)
    if not rows:
        return "no records"
    out = []
    for r in rows:
        out.append(
            f"{r.get('request_id', '?')} [{r.get('kind', '?')}] "
            f"{r.get('from', '?')} {(r.get('at') or '')[:16].replace('T', ' ')}\n"
            f"  {r.get('action', '')}"
        )
    return "\n".join(out)


@mcp.resource(
    BOARD_UI_URI,
    name="gate board UI",
    description="gate の判断履歴を時系列で描く HTML (MCP Apps)",
    mime_type="text/html",
)
async def gate_board_ui() -> str:
    rows = await _board_rows(30)
    # ⚠️ `</script>` を含む文字列が substrate に入ると HTML を破壊するので、
    #    JSON 埋め込み時にエスケープする (action/reason は自由文)。
    payload = json.dumps(rows, ensure_ascii=False).replace("</", "<\\/")
    return _BOARD_HTML.replace("window.__GATE_BOARD__ || null", payload)


# ---------------------------------------------------------------------------
# Entrypoint
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    mcp.run(transport="stdio")
