"""gate-mcp — guild-cli gate commands as MCP tools.

Thin subprocess wrapper around `node bin/gate.mjs`.
Designed for Claude Code integration via .mcp.json.

Requires: mcp >= 1.25.0 (FastMCP)
"""

from __future__ import annotations

import asyncio
import json
import os
from pathlib import Path
from typing import Any

from mcp.server.fastmcp import FastMCP

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

GUILD_CLI_DIR = os.environ.get(
    "GUILD_CLI_DIR",
    str(Path(__file__).resolve().parent.parent),
)
GATE_BIN = str(Path(GUILD_CLI_DIR) / "bin" / "gate.mjs")
GUILD_BIN = str(Path(GUILD_CLI_DIR) / "bin" / "guild.mjs")

# content_root: where guild.config.yaml lives
_DEFAULT_CONTENT_ROOT = os.environ.get("GATE_CONTENT_ROOT", "")
_PROJECTS_DIR = os.environ.get(
    "GATE_PROJECTS_DIR",
    str(Path(_DEFAULT_CONTENT_ROOT) / "projects") if _DEFAULT_CONTENT_ROOT else "",
)

# Mutable — switched by gate_switch_project()
_current_content_root = _DEFAULT_CONTENT_ROOT
_current_project: str | None = None

mcp = FastMCP(
    "gate-mcp",
    instructions="guild-cli gate commands as MCP tools. Supports project switching via gate_switch_project().",
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _cwd() -> str | None:
    """Return the current content root for subprocess cwd."""
    return _current_content_root or None


async def _run_gate(*args: str, stdin_text: str | None = None) -> str:
    """Run gate CLI and return stdout. Raises on non-zero exit."""
    cmd = ["node", GATE_BIN, *args]
    proc = await asyncio.create_subprocess_exec(
        *cmd,
        stdin=asyncio.subprocess.PIPE if stdin_text else None,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
        cwd=_cwd(),
    )
    stdout, stderr = await proc.communicate(
        input=stdin_text.encode() if stdin_text else None
    )
    out = stdout.decode().strip()
    err = stderr.decode().strip()
    if proc.returncode != 0:
        raise RuntimeError(f"gate exited {proc.returncode}: {err or out}")
    # Append stderr warnings if any
    if err:
        out = f"{out}\n[stderr] {err}"
    return out


async def _run_guild(*args: str) -> str:
    """Run guild CLI and return stdout."""
    cmd = ["node", GUILD_BIN, *args]
    proc = await asyncio.create_subprocess_exec(
        *cmd,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
        cwd=_cwd(),
    )
    stdout, stderr = await proc.communicate()
    out = stdout.decode().strip()
    err = stderr.decode().strip()
    if proc.returncode != 0:
        raise RuntimeError(f"guild exited {proc.returncode}: {err or out}")
    if err:
        out = f"{out}\n[stderr] {err}"
    return out


def _flag(name: str, value: str | None) -> list[str]:
    """Build --name value if value is truthy."""
    return [f"--{name}", value] if value else []


# ---------------------------------------------------------------------------
# Project switching
# ---------------------------------------------------------------------------

_PROJECT_CONFIG_TEMPLATE = """\
# Auto-generated by gate-mcp for project: {project}
content_root: .
host_names: [eris, nao]
paths:
  members: members
  requests: requests
  issues: issues
  inbox: inbox
"""


def _project_dir(project: str) -> Path:
    """Return the directory for a named project. Validates path stays under PROJECTS_DIR."""
    if not project or "/" in project or "\\" in project or project in (".", ".."):
        raise ValueError(f"Invalid project name: {project!r}")
    resolved = (Path(_PROJECTS_DIR) / project).resolve()
    base = Path(_PROJECTS_DIR).resolve()
    if not str(resolved).startswith(str(base) + os.sep) and resolved != base:
        raise ValueError(f"Project path escapes base: {project!r}")
    return resolved


@mcp.tool()
async def gate_switch_project(project: str | None = None) -> str:
    """Switch gate context to a project. Pass None or empty string to return to THS global.

    If the project directory doesn't exist yet, use gate_init_project() first.
    """
    global _current_content_root, _current_project

    if not project:
        _current_content_root = _DEFAULT_CONTENT_ROOT
        _current_project = None
        return f"Switched to global content root: {_DEFAULT_CONTENT_ROOT}"

    proj_dir = _project_dir(project)
    if not proj_dir.exists():
        return f"Project '{project}' not found at {proj_dir}. Use gate_init_project('{project}') to create it."

    config_file = proj_dir / "guild.config.yaml"
    if not config_file.exists():
        return f"Project directory exists but guild.config.yaml is missing at {config_file}."

    _current_content_root = str(proj_dir)
    _current_project = project
    return f"Switched to project '{project}' at {proj_dir}"


@mcp.tool()
async def gate_init_project(project: str) -> str:
    """Initialize a new project with guild.config.yaml, shared members, and empty request/issue dirs."""
    proj_dir = _project_dir(project)

    if proj_dir.exists() and (proj_dir / "guild.config.yaml").exists():
        return f"Project '{project}' already exists at {proj_dir}"

    # Create directories
    for subdir in ["requests/pending", "requests/completed", "issues", "inbox"]:
        (proj_dir / subdir).mkdir(parents=True, exist_ok=True)

    # Symlink members from global content root (shared across projects)
    members_link = proj_dir / "members"
    if not members_link.exists():
        global_members = Path(_DEFAULT_CONTENT_ROOT) / "members"
        if global_members.exists():
            members_link.symlink_to(global_members.resolve())

    # Write config
    config_file = proj_dir / "guild.config.yaml"
    config_file.write_text(_PROJECT_CONFIG_TEMPLATE.format(project=project))

    return f"Initialized project '{project}' at {proj_dir}\n  members: symlinked from global\n  requests/issues/inbox: project-local"


@mcp.tool()
async def gate_list_projects() -> str:
    """List available gate projects."""
    global _current_project
    projects_dir = Path(_PROJECTS_DIR)
    if not projects_dir.exists():
        return "No projects directory found."

    projects = sorted(
        d.name for d in projects_dir.iterdir()
        if d.is_dir() and (d / "guild.config.yaml").exists()
    )

    if not projects:
        return "No projects initialized yet. Use gate_init_project() to create one."

    lines = []
    for p in projects:
        marker = " (active)" if p == _current_project else ""
        lines.append(f"  - {p}{marker}")

    current = _current_project or "(global)"
    return f"Current: {current}\nProjects:\n" + "\n".join(lines)


# ---------------------------------------------------------------------------
# Read tools
# ---------------------------------------------------------------------------

@mcp.tool()
async def gate_tail(n: int = 20) -> str:
    """Show the N most recent utterances (reviews, status changes) across all actors."""
    return await _run_gate("tail", str(n))


@mcp.tool()
async def gate_show(request_id: str, format: str = "text") -> str:
    """Show details of a specific request. format: 'text' or 'json'."""
    return await _run_gate("show", request_id, "--format", format)


@mcp.tool()
async def gate_list(state: str = "pending", for_actor: str | None = None,
                    from_actor: str | None = None) -> str:
    """List requests filtered by state. States: pending|approved|executing|completed|failed|denied."""
    args = ["list", "--state", state]
    args += _flag("for", for_actor)
    args += _flag("from", from_actor)
    return await _run_gate(*args)


@mcp.tool()
async def gate_pending(for_actor: str | None = None) -> str:
    """Shortcut for listing pending requests."""
    args = ["pending"]
    args += _flag("for", for_actor)
    return await _run_gate(*args)


@mcp.tool()
async def gate_voices(name: str, lense: str | None = None,
                      verdict: str | None = None, limit: int | None = None,
                      format: str = "text") -> str:
    """Show cross-cutting history for a specific actor."""
    args = ["voices", name, "--format", format]
    args += _flag("lense", lense)
    args += _flag("verdict", verdict)
    if limit:
        args += ["--limit", str(limit)]
    return await _run_gate(*args)


@mcp.tool()
async def gate_chain(id: str) -> str:
    """Show the chain of related requests/issues for a given ID."""
    return await _run_gate("chain", id)


# ---------------------------------------------------------------------------
# Write tools — request lifecycle
# ---------------------------------------------------------------------------

@mcp.tool()
async def gate_request(from_actor: str, action: str, reason: str,
                       executor: str | None = None,
                       auto_review: str | None = None,
                       target: str | None = None) -> str:
    """Create a new request."""
    args = ["request", "--from", from_actor, "--action", action, "--reason", reason]
    args += _flag("executor", executor)
    args += _flag("auto-review", auto_review)
    args += _flag("target", target)
    return await _run_gate(*args)


@mcp.tool()
async def gate_fast_track(from_actor: str, action: str, reason: str,
                          executor: str | None = None,
                          auto_review: str | None = None,
                          note: str | None = None) -> str:
    """One-shot request: pending → approved → executing → completed in one call."""
    args = ["fast-track", "--from", from_actor, "--action", action, "--reason", reason]
    args += _flag("executor", executor)
    args += _flag("auto-review", auto_review)
    args += _flag("note", note)
    return await _run_gate(*args)


@mcp.tool()
async def gate_approve(request_id: str, by: str, note: str | None = None) -> str:
    """Approve a pending request."""
    args = ["approve", request_id, "--by", by]
    args += _flag("note", note)
    return await _run_gate(*args)


@mcp.tool()
async def gate_execute(request_id: str, by: str, note: str | None = None) -> str:
    """Mark a request as executing."""
    args = ["execute", request_id, "--by", by]
    args += _flag("note", note)
    return await _run_gate(*args)


@mcp.tool()
async def gate_complete(request_id: str, by: str, note: str | None = None) -> str:
    """Mark a request as completed."""
    args = ["complete", request_id, "--by", by]
    args += _flag("note", note)
    return await _run_gate(*args)


@mcp.tool()
async def gate_deny(request_id: str, by: str, reason: str) -> str:
    """Deny a pending request."""
    return await _run_gate("deny", request_id, "--by", by, reason)


@mcp.tool()
async def gate_fail(request_id: str, by: str, reason: str) -> str:
    """Mark a request as failed."""
    return await _run_gate("fail", request_id, "--by", by, reason)


# ---------------------------------------------------------------------------
# Write tools — review
# ---------------------------------------------------------------------------

@mcp.tool()
async def gate_review(request_id: str, by: str, lense: str, verdict: str,
                      comment: str | None = None) -> str:
    """Add a review to a request. lense: devil|layer|cognitive|user. verdict: ok|concern|reject."""
    args = ["review", request_id, "--by", by, "--lense", lense, "--verdict", verdict]
    if comment:
        args += ["--comment", comment]
    return await _run_gate(*args)


# ---------------------------------------------------------------------------
# Issues
# ---------------------------------------------------------------------------

@mcp.tool()
async def gate_issues_list(state: str | None = None) -> str:
    """List issues. Optional state filter: open|in_progress|deferred|resolved."""
    args = ["issues", "list"]
    args += _flag("state", state)
    return await _run_gate(*args)


@mcp.tool()
async def gate_issues_add(from_actor: str, severity: str, area: str,
                          text: str) -> str:
    """Add a new issue. severity: low|med|high. area: free text."""
    return await _run_gate("issues", "add", "--from", from_actor,
                           "--severity", severity, "--area", area, text)


@mcp.tool()
async def gate_issues_transition(issue_id: str, verb: str) -> str:
    """Transition an issue state. verb: resolve|defer|start|reopen."""
    if verb not in ("resolve", "defer", "start", "reopen"):
        raise ValueError(f"Invalid verb: {verb}. Use resolve|defer|start|reopen")
    return await _run_gate("issues", verb, issue_id)


# ---------------------------------------------------------------------------
# Messages
# ---------------------------------------------------------------------------

@mcp.tool()
async def gate_message(from_actor: str, to: str, text: str) -> str:
    """Send a direct message to another member."""
    return await _run_gate("message", "--from", from_actor, "--to", to, "--text", text)


@mcp.tool()
async def gate_broadcast(from_actor: str, text: str) -> str:
    """Broadcast a message to all members."""
    return await _run_gate("broadcast", "--from", from_actor, "--text", text)


@mcp.tool()
async def gate_inbox(for_actor: str) -> str:
    """Read inbox messages for a member."""
    return await _run_gate("inbox", "--for", for_actor)


# ---------------------------------------------------------------------------
# Guild (member management)
# ---------------------------------------------------------------------------

@mcp.tool()
async def guild_list() -> str:
    """List all guild members."""
    return await _run_guild("list")


@mcp.tool()
async def guild_show(name: str) -> str:
    """Show member details."""
    return await _run_guild("show", name)


# ---------------------------------------------------------------------------
# Status (agent orientation)
# ---------------------------------------------------------------------------

@mcp.tool()
async def gate_status(for_actor: str | None = None, format: str = "json") -> str:
    """Agent orientation: pending/approved/executing counts, open issues, inbox unread.
    Default JSON output. Use --format text for human-readable."""
    args = ["status", "--format", format]
    args += _flag("for", for_actor)
    return await _run_gate(*args)


# ---------------------------------------------------------------------------
# Diagnostic
# ---------------------------------------------------------------------------

@mcp.tool()
async def gate_doctor(format: str = "text") -> str:
    """Run read-only health check over the content root."""
    args = ["doctor"]
    if format == "json":
        args += ["--format", "json"]
    elif format == "summary":
        args += ["--summary"]
    return await _run_gate(*args)


# ---------------------------------------------------------------------------
# Entrypoint
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    mcp.run(transport="stdio")
